// src/components/app/lattice/blockReflows.ts

import type { BlockSlot } from './blockTemplates';

// Generated data. For each base template, one layout per slot that could be expanded: the
// expanded card takes the 6x6 gear and the other eleven fall back to smaller gears so the
// block stays exactly covered. Indexed by the ORIGINAL slot, so a card keeps its identity
// through the change; the solver picked, out of every exact cover, the arrangement that moves
// the existing cards least. Do not hand-edit - regenerate if the templates or gears change.

export const BLOCK_REFLOWS: BlockSlot[][][] = [
    // 变体 0 的 12 张让位表，下标 = 被展开的槽位
    [
        // 展开槽位 0
        [
            { x: 0, y: 0, cols: 6, rows: 6 },
            { x: 6, y: 0, cols: 4, rows: 4 },
            { x: 10, y: 0, cols: 2, rows: 2 },
            { x: 2, y: 6, cols: 2, rows: 2 },
            { x: 10, y: 2, cols: 2, rows: 4 },
            { x: 0, y: 6, cols: 2, rows: 2 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 6, y: 4, cols: 2, rows: 2 },
            { x: 6, y: 6, cols: 2, rows: 2 },
            { x: 8, y: 6, cols: 2, rows: 2 },
            { x: 8, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 6, cols: 2, rows: 2 },
        ],
        // 展开槽位 1
        [
            { x: 0, y: 0, cols: 3, rows: 2 },
            { x: 3, y: 0, cols: 6, rows: 6 },
            { x: 9, y: 0, cols: 3, rows: 2 },
            { x: 0, y: 2, cols: 3, rows: 2 },
            { x: 9, y: 2, cols: 3, rows: 2 },
            { x: 0, y: 4, cols: 3, rows: 2 },
            { x: 3, y: 6, cols: 3, rows: 2 },
            { x: 6, y: 6, cols: 2, rows: 2 },
            { x: 0, y: 6, cols: 3, rows: 2 },
            { x: 8, y: 6, cols: 2, rows: 2 },
            { x: 10, y: 6, cols: 2, rows: 2 },
            { x: 9, y: 4, cols: 3, rows: 2 },
        ],
        // 展开槽位 2
        [
            { x: 0, y: 0, cols: 3, rows: 2 },
            { x: 3, y: 0, cols: 3, rows: 4 },
            { x: 6, y: 0, cols: 6, rows: 6 },
            { x: 0, y: 2, cols: 3, rows: 2 },
            { x: 10, y: 6, cols: 2, rows: 2 },
            { x: 0, y: 4, cols: 2, rows: 4 },
            { x: 4, y: 4, cols: 2, rows: 2 },
            { x: 6, y: 6, cols: 2, rows: 2 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 8, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 4, cols: 2, rows: 2 },
        ],
        // 展开槽位 3
        [
            { x: 2, y: 0, cols: 2, rows: 2 },
            { x: 4, y: 0, cols: 6, rows: 2 },
            { x: 8, y: 2, cols: 2, rows: 2 },
            { x: 0, y: 2, cols: 6, rows: 6 },
            { x: 10, y: 0, cols: 2, rows: 6 },
            { x: 0, y: 0, cols: 2, rows: 2 },
            { x: 6, y: 2, cols: 2, rows: 2 },
            { x: 6, y: 4, cols: 2, rows: 2 },
            { x: 6, y: 6, cols: 2, rows: 2 },
            { x: 8, y: 6, cols: 2, rows: 2 },
            { x: 8, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 6, cols: 2, rows: 2 },
        ],
        // 展开槽位 4
        [
            { x: 0, y: 0, cols: 3, rows: 2 },
            { x: 3, y: 0, cols: 4, rows: 2 },
            { x: 10, y: 0, cols: 2, rows: 2 },
            { x: 0, y: 2, cols: 2, rows: 3 },
            { x: 6, y: 2, cols: 6, rows: 6 },
            { x: 0, y: 5, cols: 2, rows: 3 },
            { x: 2, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 6, cols: 2, rows: 2 },
            { x: 7, y: 0, cols: 3, rows: 2 },
            { x: 2, y: 2, cols: 4, rows: 2 },
        ],
        // 展开槽位 5
        [
            { x: 0, y: 0, cols: 3, rows: 2 },
            { x: 5, y: 0, cols: 4, rows: 2 },
            { x: 9, y: 0, cols: 3, rows: 2 },
            { x: 3, y: 0, cols: 2, rows: 2 },
            { x: 8, y: 2, cols: 4, rows: 2 },
            { x: 0, y: 2, cols: 6, rows: 6 },
            { x: 6, y: 2, cols: 2, rows: 2 },
            { x: 6, y: 4, cols: 2, rows: 2 },
            { x: 6, y: 6, cols: 2, rows: 2 },
            { x: 8, y: 4, cols: 2, rows: 4 },
            { x: 10, y: 6, cols: 2, rows: 2 },
            { x: 10, y: 4, cols: 2, rows: 2 },
        ],
        // 展开槽位 6
        [
            { x: 0, y: 0, cols: 4, rows: 2 },
            { x: 4, y: 0, cols: 3, rows: 2 },
            { x: 9, y: 0, cols: 3, rows: 2 },
            { x: 0, y: 2, cols: 2, rows: 3 },
            { x: 10, y: 2, cols: 2, rows: 2 },
            { x: 0, y: 5, cols: 2, rows: 3 },
            { x: 4, y: 2, cols: 6, rows: 6 },
            { x: 10, y: 4, cols: 2, rows: 2 },
            { x: 2, y: 6, cols: 2, rows: 2 },
            { x: 10, y: 6, cols: 2, rows: 2 },
            { x: 7, y: 0, cols: 2, rows: 2 },
            { x: 2, y: 2, cols: 2, rows: 4 },
        ],
        // 展开槽位 7
        [
            { x: 0, y: 0, cols: 4, rows: 2 },
            { x: 4, y: 0, cols: 4, rows: 2 },
            { x: 8, y: 0, cols: 2, rows: 2 },
            { x: 0, y: 2, cols: 2, rows: 3 },
            { x: 10, y: 0, cols: 2, rows: 2 },
            { x: 0, y: 5, cols: 2, rows: 3 },
            { x: 4, y: 4, cols: 2, rows: 2 },
            { x: 6, y: 2, cols: 6, rows: 6 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 4, cols: 2, rows: 2 },
            { x: 2, y: 2, cols: 4, rows: 2 },
        ],
        // 展开槽位 8
        [
            { x: 0, y: 0, cols: 4, rows: 2 },
            { x: 4, y: 0, cols: 3, rows: 2 },
            { x: 9, y: 0, cols: 3, rows: 2 },
            { x: 0, y: 2, cols: 2, rows: 3 },
            { x: 10, y: 2, cols: 2, rows: 2 },
            { x: 0, y: 5, cols: 2, rows: 3 },
            { x: 2, y: 2, cols: 2, rows: 4 },
            { x: 10, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 2, cols: 6, rows: 6 },
            { x: 2, y: 6, cols: 2, rows: 2 },
            { x: 10, y: 6, cols: 2, rows: 2 },
            { x: 7, y: 0, cols: 2, rows: 2 },
        ],
        // 展开槽位 9
        [
            { x: 0, y: 0, cols: 4, rows: 2 },
            { x: 4, y: 0, cols: 4, rows: 2 },
            { x: 8, y: 0, cols: 2, rows: 2 },
            { x: 0, y: 2, cols: 2, rows: 3 },
            { x: 10, y: 0, cols: 2, rows: 2 },
            { x: 0, y: 5, cols: 2, rows: 3 },
            { x: 2, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 6, y: 2, cols: 6, rows: 6 },
            { x: 2, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 2, cols: 4, rows: 2 },
        ],
        // 展开槽位 10
        [
            { x: 0, y: 0, cols: 4, rows: 2 },
            { x: 4, y: 0, cols: 4, rows: 2 },
            { x: 8, y: 0, cols: 2, rows: 2 },
            { x: 0, y: 2, cols: 2, rows: 3 },
            { x: 10, y: 0, cols: 2, rows: 2 },
            { x: 0, y: 5, cols: 2, rows: 3 },
            { x: 2, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 6, cols: 2, rows: 2 },
            { x: 6, y: 2, cols: 6, rows: 6 },
            { x: 2, y: 2, cols: 4, rows: 2 },
        ],
        // 展开槽位 11
        [
            { x: 0, y: 0, cols: 4, rows: 2 },
            { x: 4, y: 0, cols: 4, rows: 2 },
            { x: 8, y: 0, cols: 2, rows: 2 },
            { x: 0, y: 2, cols: 2, rows: 3 },
            { x: 10, y: 0, cols: 2, rows: 2 },
            { x: 0, y: 5, cols: 2, rows: 3 },
            { x: 2, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 2, cols: 4, rows: 2 },
            { x: 6, y: 2, cols: 6, rows: 6 },
        ],
    ],
    // 变体 1 的 12 张让位表，下标 = 被展开的槽位
    [
        // 展开槽位 0
        [
            { x: 0, y: 0, cols: 6, rows: 6 },
            { x: 6, y: 0, cols: 2, rows: 2 },
            { x: 6, y: 2, cols: 2, rows: 2 },
            { x: 8, y: 0, cols: 4, rows: 4 },
            { x: 2, y: 6, cols: 2, rows: 2 },
            { x: 6, y: 4, cols: 2, rows: 4 },
            { x: 8, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 4, cols: 2, rows: 2 },
            { x: 0, y: 6, cols: 2, rows: 2 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 8, y: 6, cols: 2, rows: 2 },
            { x: 10, y: 6, cols: 2, rows: 2 },
        ],
        // 展开槽位 1
        [
            { x: 0, y: 0, cols: 2, rows: 3 },
            { x: 2, y: 0, cols: 6, rows: 6 },
            { x: 8, y: 2, cols: 4, rows: 2 },
            { x: 8, y: 0, cols: 4, rows: 2 },
            { x: 0, y: 3, cols: 2, rows: 2 },
            { x: 6, y: 6, cols: 2, rows: 2 },
            { x: 8, y: 4, cols: 2, rows: 4 },
            { x: 10, y: 4, cols: 2, rows: 2 },
            { x: 0, y: 5, cols: 2, rows: 3 },
            { x: 2, y: 6, cols: 2, rows: 2 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 10, y: 6, cols: 2, rows: 2 },
        ],
        // 展开槽位 2
        [
            { x: 0, y: 0, cols: 2, rows: 3 },
            { x: 2, y: 0, cols: 2, rows: 3 },
            { x: 4, y: 0, cols: 6, rows: 6 },
            { x: 10, y: 0, cols: 2, rows: 4 },
            { x: 0, y: 3, cols: 4, rows: 2 },
            { x: 6, y: 6, cols: 2, rows: 2 },
            { x: 8, y: 6, cols: 2, rows: 2 },
            { x: 10, y: 4, cols: 2, rows: 2 },
            { x: 0, y: 5, cols: 2, rows: 3 },
            { x: 2, y: 5, cols: 2, rows: 3 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 10, y: 6, cols: 2, rows: 2 },
        ],
        // 展开槽位 3
        [
            { x: 0, y: 0, cols: 2, rows: 3 },
            { x: 2, y: 0, cols: 2, rows: 3 },
            { x: 4, y: 0, cols: 2, rows: 4 },
            { x: 6, y: 0, cols: 6, rows: 6 },
            { x: 0, y: 3, cols: 4, rows: 2 },
            { x: 6, y: 6, cols: 2, rows: 2 },
            { x: 8, y: 6, cols: 2, rows: 2 },
            { x: 10, y: 6, cols: 2, rows: 2 },
            { x: 0, y: 5, cols: 2, rows: 3 },
            { x: 2, y: 5, cols: 2, rows: 3 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 4, y: 4, cols: 2, rows: 2 },
        ],
        // 展开槽位 4
        [
            { x: 0, y: 0, cols: 2, rows: 2 },
            { x: 2, y: 0, cols: 2, rows: 2 },
            { x: 4, y: 0, cols: 4, rows: 2 },
            { x: 8, y: 0, cols: 4, rows: 4 },
            { x: 0, y: 2, cols: 6, rows: 6 },
            { x: 6, y: 4, cols: 2, rows: 2 },
            { x: 8, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 4, cols: 2, rows: 2 },
            { x: 6, y: 6, cols: 2, rows: 2 },
            { x: 6, y: 2, cols: 2, rows: 2 },
            { x: 8, y: 6, cols: 2, rows: 2 },
            { x: 10, y: 6, cols: 2, rows: 2 },
        ],
        // 展开槽位 5
        [
            { x: 0, y: 0, cols: 2, rows: 4 },
            { x: 2, y: 0, cols: 2, rows: 3 },
            { x: 4, y: 0, cols: 4, rows: 2 },
            { x: 8, y: 0, cols: 2, rows: 2 },
            { x: 2, y: 3, cols: 2, rows: 2 },
            { x: 6, y: 2, cols: 6, rows: 6 },
            { x: 4, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 0, cols: 2, rows: 2 },
            { x: 0, y: 4, cols: 2, rows: 4 },
            { x: 2, y: 5, cols: 2, rows: 3 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 4, y: 2, cols: 2, rows: 2 },
        ],
        // 展开槽位 6
        [
            { x: 0, y: 0, cols: 2, rows: 4 },
            { x: 2, y: 0, cols: 2, rows: 3 },
            { x: 4, y: 0, cols: 4, rows: 2 },
            { x: 8, y: 0, cols: 2, rows: 2 },
            { x: 2, y: 3, cols: 2, rows: 2 },
            { x: 4, y: 4, cols: 2, rows: 2 },
            { x: 6, y: 2, cols: 6, rows: 6 },
            { x: 10, y: 0, cols: 2, rows: 2 },
            { x: 0, y: 4, cols: 2, rows: 4 },
            { x: 2, y: 5, cols: 2, rows: 3 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 4, y: 2, cols: 2, rows: 2 },
        ],
        // 展开槽位 7
        [
            { x: 0, y: 0, cols: 2, rows: 4 },
            { x: 2, y: 0, cols: 2, rows: 3 },
            { x: 4, y: 0, cols: 4, rows: 2 },
            { x: 8, y: 0, cols: 2, rows: 2 },
            { x: 2, y: 3, cols: 2, rows: 2 },
            { x: 4, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 6, y: 2, cols: 6, rows: 6 },
            { x: 0, y: 4, cols: 2, rows: 4 },
            { x: 2, y: 5, cols: 2, rows: 3 },
            { x: 4, y: 2, cols: 2, rows: 2 },
            { x: 10, y: 0, cols: 2, rows: 2 },
        ],
        // 展开槽位 8
        [
            { x: 0, y: 0, cols: 2, rows: 2 },
            { x: 4, y: 0, cols: 2, rows: 2 },
            { x: 6, y: 0, cols: 2, rows: 3 },
            { x: 8, y: 0, cols: 4, rows: 4 },
            { x: 2, y: 0, cols: 2, rows: 2 },
            { x: 6, y: 6, cols: 2, rows: 2 },
            { x: 8, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 4, cols: 2, rows: 2 },
            { x: 0, y: 2, cols: 6, rows: 6 },
            { x: 6, y: 3, cols: 2, rows: 3 },
            { x: 8, y: 6, cols: 2, rows: 2 },
            { x: 10, y: 6, cols: 2, rows: 2 },
        ],
        // 展开槽位 9
        [
            { x: 0, y: 0, cols: 2, rows: 2 },
            { x: 2, y: 0, cols: 2, rows: 2 },
            { x: 4, y: 0, cols: 4, rows: 2 },
            { x: 8, y: 0, cols: 4, rows: 4 },
            { x: 0, y: 2, cols: 2, rows: 2 },
            { x: 8, y: 4, cols: 2, rows: 2 },
            { x: 8, y: 6, cols: 2, rows: 2 },
            { x: 10, y: 4, cols: 2, rows: 2 },
            { x: 0, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 2, cols: 6, rows: 6 },
            { x: 0, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 6, cols: 2, rows: 2 },
        ],
        // 展开槽位 10
        [
            { x: 0, y: 0, cols: 2, rows: 3 },
            { x: 2, y: 0, cols: 2, rows: 4 },
            { x: 4, y: 0, cols: 4, rows: 2 },
            { x: 8, y: 0, cols: 4, rows: 2 },
            { x: 0, y: 3, cols: 2, rows: 3 },
            { x: 2, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 2, cols: 2, rows: 2 },
            { x: 0, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 6, cols: 2, rows: 2 },
            { x: 4, y: 2, cols: 6, rows: 6 },
            { x: 10, y: 6, cols: 2, rows: 2 },
        ],
        // 展开槽位 11
        [
            { x: 0, y: 0, cols: 2, rows: 4 },
            { x: 2, y: 0, cols: 2, rows: 3 },
            { x: 4, y: 0, cols: 4, rows: 2 },
            { x: 8, y: 0, cols: 2, rows: 2 },
            { x: 2, y: 3, cols: 2, rows: 2 },
            { x: 4, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 10, y: 0, cols: 2, rows: 2 },
            { x: 0, y: 4, cols: 2, rows: 4 },
            { x: 2, y: 5, cols: 2, rows: 3 },
            { x: 4, y: 2, cols: 2, rows: 2 },
            { x: 6, y: 2, cols: 6, rows: 6 },
        ],
    ],
    // 变体 2 的 12 张让位表，下标 = 被展开的槽位
    [
        // 展开槽位 0
        [
            { x: 0, y: 0, cols: 6, rows: 6 },
            { x: 6, y: 0, cols: 6, rows: 2 },
            { x: 8, y: 2, cols: 2, rows: 4 },
            { x: 10, y: 2, cols: 2, rows: 3 },
            { x: 0, y: 6, cols: 2, rows: 2 },
            { x: 6, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 5, cols: 2, rows: 3 },
            { x: 2, y: 6, cols: 2, rows: 2 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 6, y: 6, cols: 2, rows: 2 },
            { x: 8, y: 6, cols: 2, rows: 2 },
            { x: 6, y: 2, cols: 2, rows: 2 },
        ],
        // 展开槽位 1
        [
            { x: 0, y: 0, cols: 4, rows: 4 },
            { x: 6, y: 0, cols: 6, rows: 6 },
            { x: 6, y: 6, cols: 2, rows: 2 },
            { x: 8, y: 6, cols: 2, rows: 2 },
            { x: 0, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 6, cols: 2, rows: 2 },
            { x: 0, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 6, cols: 2, rows: 2 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 0, cols: 2, rows: 4 },
        ],
        // 展开槽位 2
        [
            { x: 0, y: 0, cols: 4, rows: 4 },
            { x: 8, y: 0, cols: 2, rows: 2 },
            { x: 6, y: 2, cols: 6, rows: 6 },
            { x: 6, y: 0, cols: 2, rows: 2 },
            { x: 0, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 0, cols: 2, rows: 2 },
            { x: 0, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 6, cols: 2, rows: 2 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 0, cols: 2, rows: 4 },
        ],
        // 展开槽位 3
        [
            { x: 0, y: 0, cols: 4, rows: 4 },
            { x: 8, y: 0, cols: 2, rows: 2 },
            { x: 4, y: 4, cols: 2, rows: 2 },
            { x: 6, y: 2, cols: 6, rows: 6 },
            { x: 0, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 2, cols: 2, rows: 2 },
            { x: 10, y: 0, cols: 2, rows: 2 },
            { x: 0, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 6, cols: 2, rows: 2 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 0, cols: 4, rows: 2 },
        ],
        // 展开槽位 4
        [
            { x: 2, y: 0, cols: 4, rows: 2 },
            { x: 6, y: 0, cols: 6, rows: 2 },
            { x: 6, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 4, cols: 2, rows: 2 },
            { x: 0, y: 2, cols: 6, rows: 6 },
            { x: 6, y: 2, cols: 2, rows: 2 },
            { x: 10, y: 6, cols: 2, rows: 2 },
            { x: 0, y: 0, cols: 2, rows: 2 },
            { x: 6, y: 6, cols: 2, rows: 2 },
            { x: 8, y: 6, cols: 2, rows: 2 },
            { x: 8, y: 4, cols: 2, rows: 2 },
            { x: 8, y: 2, cols: 4, rows: 2 },
        ],
        // 展开槽位 5
        [
            { x: 0, y: 0, cols: 4, rows: 4 },
            { x: 8, y: 0, cols: 2, rows: 2 },
            { x: 10, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 2, cols: 2, rows: 2 },
            { x: 0, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 2, cols: 6, rows: 6 },
            { x: 10, y: 6, cols: 2, rows: 2 },
            { x: 0, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 0, cols: 4, rows: 2 },
            { x: 10, y: 0, cols: 2, rows: 2 },
        ],
        // 展开槽位 6
        [
            { x: 0, y: 0, cols: 4, rows: 4 },
            { x: 8, y: 0, cols: 2, rows: 2 },
            { x: 4, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 0, cols: 2, rows: 2 },
            { x: 0, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 2, cols: 2, rows: 2 },
            { x: 6, y: 2, cols: 6, rows: 6 },
            { x: 0, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 6, cols: 2, rows: 2 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 0, cols: 4, rows: 2 },
        ],
        // 展开槽位 7
        [
            { x: 0, y: 0, cols: 4, rows: 2 },
            { x: 6, y: 0, cols: 6, rows: 2 },
            { x: 6, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 2, cols: 2, rows: 3 },
            { x: 4, y: 0, cols: 2, rows: 2 },
            { x: 6, y: 2, cols: 2, rows: 2 },
            { x: 10, y: 5, cols: 2, rows: 3 },
            { x: 0, y: 2, cols: 6, rows: 6 },
            { x: 6, y: 6, cols: 2, rows: 2 },
            { x: 8, y: 6, cols: 2, rows: 2 },
            { x: 8, y: 4, cols: 2, rows: 2 },
            { x: 8, y: 2, cols: 2, rows: 2 },
        ],
        // 展开槽位 8
        [
            { x: 0, y: 0, cols: 6, rows: 2 },
            { x: 6, y: 0, cols: 6, rows: 2 },
            { x: 8, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 2, cols: 2, rows: 2 },
            { x: 0, y: 4, cols: 2, rows: 2 },
            { x: 0, y: 2, cols: 2, rows: 2 },
            { x: 10, y: 6, cols: 2, rows: 2 },
            { x: 0, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 2, cols: 6, rows: 6 },
            { x: 8, y: 6, cols: 2, rows: 2 },
            { x: 8, y: 2, cols: 2, rows: 2 },
            { x: 10, y: 4, cols: 2, rows: 2 },
        ],
        // 展开槽位 9
        [
            { x: 0, y: 0, cols: 4, rows: 4 },
            { x: 8, y: 0, cols: 2, rows: 2 },
            { x: 10, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 2, cols: 2, rows: 2 },
            { x: 0, y: 4, cols: 2, rows: 2 },
            { x: 2, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 6, cols: 2, rows: 2 },
            { x: 0, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 6, cols: 2, rows: 2 },
            { x: 4, y: 2, cols: 6, rows: 6 },
            { x: 4, y: 0, cols: 4, rows: 2 },
            { x: 10, y: 0, cols: 2, rows: 2 },
        ],
        // 展开槽位 10
        [
            { x: 0, y: 0, cols: 4, rows: 4 },
            { x: 8, y: 0, cols: 2, rows: 2 },
            { x: 4, y: 4, cols: 2, rows: 2 },
            { x: 6, y: 0, cols: 2, rows: 2 },
            { x: 0, y: 4, cols: 2, rows: 2 },
            { x: 2, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 0, cols: 2, rows: 2 },
            { x: 0, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 6, cols: 2, rows: 2 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 6, y: 2, cols: 6, rows: 6 },
            { x: 4, y: 0, cols: 2, rows: 4 },
        ],
        // 展开槽位 11
        [
            { x: 0, y: 0, cols: 4, rows: 4 },
            { x: 8, y: 0, cols: 2, rows: 2 },
            { x: 4, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 0, cols: 4, rows: 2 },
            { x: 0, y: 4, cols: 2, rows: 2 },
            { x: 4, y: 2, cols: 2, rows: 2 },
            { x: 10, y: 0, cols: 2, rows: 2 },
            { x: 0, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 6, cols: 2, rows: 2 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 4, cols: 2, rows: 2 },
            { x: 6, y: 2, cols: 6, rows: 6 },
        ],
    ],
    // 变体 3 的 12 张让位表，下标 = 被展开的槽位
    [
        // 展开槽位 0
        [
            { x: 0, y: 0, cols: 6, rows: 6 },
            { x: 6, y: 2, cols: 2, rows: 2 },
            { x: 6, y: 0, cols: 2, rows: 2 },
            { x: 8, y: 0, cols: 2, rows: 6 },
            { x: 10, y: 0, cols: 2, rows: 2 },
            { x: 0, y: 6, cols: 2, rows: 2 },
            { x: 6, y: 6, cols: 2, rows: 2 },
            { x: 6, y: 4, cols: 2, rows: 2 },
            { x: 8, y: 6, cols: 2, rows: 2 },
            { x: 10, y: 2, cols: 2, rows: 6 },
            { x: 2, y: 6, cols: 2, rows: 2 },
            { x: 4, y: 6, cols: 2, rows: 2 },
        ],
        // 展开槽位 1
        [
            { x: 0, y: 0, cols: 2, rows: 2 },
            { x: 2, y: 0, cols: 6, rows: 6 },
            { x: 8, y: 0, cols: 2, rows: 3 },
            { x: 8, y: 3, cols: 2, rows: 3 },
            { x: 10, y: 0, cols: 2, rows: 4 },
            { x: 0, y: 2, cols: 2, rows: 2 },
            { x: 6, y: 6, cols: 2, rows: 2 },
            { x: 4, y: 6, cols: 2, rows: 2 },
            { x: 8, y: 6, cols: 2, rows: 2 },
            { x: 10, y: 4, cols: 2, rows: 4 },
            { x: 0, y: 4, cols: 2, rows: 4 },
            { x: 2, y: 6, cols: 2, rows: 2 },
        ],
        // 展开槽位 2
        [
            { x: 0, y: 0, cols: 2, rows: 2 },
            { x: 2, y: 0, cols: 2, rows: 3 },
            { x: 4, y: 0, cols: 6, rows: 6 },
            { x: 10, y: 0, cols: 2, rows: 2 },
            { x: 10, y: 2, cols: 2, rows: 3 },
            { x: 0, y: 2, cols: 2, rows: 2 },
            { x: 2, y: 3, cols: 2, rows: 2 },
            { x: 4, y: 6, cols: 6, rows: 2 },
            { x: 0, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 5, cols: 2, rows: 3 },
            { x: 0, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 5, cols: 2, rows: 3 },
        ],
        // 展开槽位 3
        [
            { x: 0, y: 0, cols: 2, rows: 2 },
            { x: 2, y: 0, cols: 2, rows: 2 },
            { x: 4, y: 0, cols: 2, rows: 4 },
            { x: 6, y: 0, cols: 6, rows: 6 },
            { x: 7, y: 6, cols: 2, rows: 2 },
            { x: 0, y: 2, cols: 2, rows: 4 },
            { x: 2, y: 2, cols: 2, rows: 2 },
            { x: 4, y: 4, cols: 2, rows: 2 },
            { x: 2, y: 4, cols: 2, rows: 4 },
            { x: 9, y: 6, cols: 3, rows: 2 },
            { x: 0, y: 6, cols: 2, rows: 2 },
            { x: 4, y: 6, cols: 3, rows: 2 },
        ],
        // 展开槽位 4
        [
            { x: 0, y: 0, cols: 2, rows: 2 },
            { x: 2, y: 0, cols: 2, rows: 2 },
            { x: 4, y: 0, cols: 2, rows: 4 },
            { x: 7, y: 6, cols: 2, rows: 2 },
            { x: 6, y: 0, cols: 6, rows: 6 },
            { x: 0, y: 2, cols: 2, rows: 4 },
            { x: 2, y: 2, cols: 2, rows: 2 },
            { x: 4, y: 4, cols: 2, rows: 2 },
            { x: 2, y: 4, cols: 2, rows: 4 },
            { x: 9, y: 6, cols: 3, rows: 2 },
            { x: 0, y: 6, cols: 2, rows: 2 },
            { x: 4, y: 6, cols: 3, rows: 2 },
        ],
        // 展开槽位 5
        [
            { x: 3, y: 0, cols: 2, rows: 2 },
            { x: 6, y: 2, cols: 2, rows: 2 },
            { x: 5, y: 0, cols: 2, rows: 2 },
            { x: 8, y: 2, cols: 2, rows: 3 },
            { x: 9, y: 0, cols: 3, rows: 2 },
            { x: 0, y: 2, cols: 6, rows: 6 },
            { x: 7, y: 0, cols: 2, rows: 2 },
            { x: 6, y: 4, cols: 2, rows: 2 },
            { x: 8, y: 5, cols: 2, rows: 3 },
            { x: 10, y: 2, cols: 2, rows: 6 },
            { x: 0, y: 0, cols: 3, rows: 2 },
            { x: 6, y: 6, cols: 2, rows: 2 },
        ],
        // 展开槽位 6
        [
            { x: 0, y: 0, cols: 2, rows: 2 },
            { x: 2, y: 0, cols: 2, rows: 2 },
            { x: 4, y: 0, cols: 6, rows: 2 },
            { x: 8, y: 2, cols: 2, rows: 2 },
            { x: 10, y: 0, cols: 2, rows: 3 },
            { x: 0, y: 2, cols: 2, rows: 3 },
            { x: 2, y: 2, cols: 6, rows: 6 },
            { x: 8, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 3, cols: 2, rows: 2 },
            { x: 10, y: 5, cols: 2, rows: 3 },
            { x: 0, y: 5, cols: 2, rows: 3 },
            { x: 8, y: 6, cols: 2, rows: 2 },
        ],
        // 展开槽位 7
        [
            { x: 0, y: 0, cols: 2, rows: 3 },
            { x: 2, y: 0, cols: 2, rows: 2 },
            { x: 4, y: 0, cols: 3, rows: 2 },
            { x: 7, y: 0, cols: 3, rows: 2 },
            { x: 10, y: 0, cols: 2, rows: 6 },
            { x: 0, y: 3, cols: 2, rows: 2 },
            { x: 2, y: 2, cols: 2, rows: 2 },
            { x: 4, y: 2, cols: 6, rows: 6 },
            { x: 2, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 6, cols: 2, rows: 2 },
            { x: 0, y: 5, cols: 2, rows: 3 },
            { x: 2, y: 6, cols: 2, rows: 2 },
        ],
        // 展开槽位 8
        [
            { x: 0, y: 0, cols: 2, rows: 2 },
            { x: 2, y: 0, cols: 2, rows: 2 },
            { x: 4, y: 0, cols: 6, rows: 2 },
            { x: 8, y: 2, cols: 2, rows: 2 },
            { x: 10, y: 0, cols: 2, rows: 3 },
            { x: 0, y: 2, cols: 2, rows: 3 },
            { x: 10, y: 3, cols: 2, rows: 2 },
            { x: 8, y: 4, cols: 2, rows: 2 },
            { x: 2, y: 2, cols: 6, rows: 6 },
            { x: 10, y: 5, cols: 2, rows: 3 },
            { x: 0, y: 5, cols: 2, rows: 3 },
            { x: 8, y: 6, cols: 2, rows: 2 },
        ],
        // 展开槽位 9
        [
            { x: 0, y: 0, cols: 2, rows: 2 },
            { x: 2, y: 0, cols: 3, rows: 2 },
            { x: 5, y: 0, cols: 3, rows: 2 },
            { x: 8, y: 0, cols: 2, rows: 2 },
            { x: 10, y: 0, cols: 2, rows: 2 },
            { x: 0, y: 2, cols: 2, rows: 3 },
            { x: 2, y: 2, cols: 2, rows: 2 },
            { x: 4, y: 2, cols: 2, rows: 6 },
            { x: 2, y: 4, cols: 2, rows: 2 },
            { x: 6, y: 2, cols: 6, rows: 6 },
            { x: 0, y: 5, cols: 2, rows: 3 },
            { x: 2, y: 6, cols: 2, rows: 2 },
        ],
        // 展开槽位 10
        [
            { x: 2, y: 0, cols: 3, rows: 2 },
            { x: 6, y: 2, cols: 2, rows: 2 },
            { x: 5, y: 0, cols: 3, rows: 2 },
            { x: 8, y: 0, cols: 4, rows: 3 },
            { x: 10, y: 3, cols: 2, rows: 2 },
            { x: 0, y: 0, cols: 2, rows: 2 },
            { x: 8, y: 3, cols: 2, rows: 3 },
            { x: 6, y: 4, cols: 2, rows: 2 },
            { x: 8, y: 6, cols: 2, rows: 2 },
            { x: 10, y: 5, cols: 2, rows: 3 },
            { x: 0, y: 2, cols: 6, rows: 6 },
            { x: 6, y: 6, cols: 2, rows: 2 },
        ],
        // 展开槽位 11
        [
            { x: 0, y: 0, cols: 2, rows: 2 },
            { x: 2, y: 0, cols: 4, rows: 2 },
            { x: 6, y: 0, cols: 2, rows: 2 },
            { x: 8, y: 0, cols: 2, rows: 4 },
            { x: 10, y: 0, cols: 2, rows: 3 },
            { x: 0, y: 2, cols: 2, rows: 2 },
            { x: 0, y: 4, cols: 2, rows: 2 },
            { x: 8, y: 4, cols: 2, rows: 2 },
            { x: 10, y: 3, cols: 2, rows: 3 },
            { x: 8, y: 6, cols: 4, rows: 2 },
            { x: 0, y: 6, cols: 2, rows: 2 },
            { x: 2, y: 2, cols: 6, rows: 6 },
        ],
    ],];
